site_name: Hogwarts Documentation
site_url: https://documentation.hogwartsnetwork.co.uk
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: pink
  features:
    - header.autohide
    - navigation.tabs
plugins:
  - search
extra:
  generator: false
  version:
    provider: mike
    default: stable
markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format